from __future__ import annotations

from frappe.custom.doctype.custom_field.custom_field import create_custom_fields


def after_install() -> None:
	create_enable_banking_custom_fields()


def after_migrate() -> None:
	create_enable_banking_custom_fields()


def before_tests() -> None:
	create_enable_banking_custom_fields()
	from enable_banking.tests.fixtures import ensure_accounting_fixtures

	ensure_accounting_fixtures()


def create_enable_banking_custom_fields() -> None:
	create_custom_fields(get_custom_fields(), update=True)


def get_custom_fields() -> dict[str, list[dict]]:
	return {
		"Bank": [
			{
				"fieldname": "enable_banking_aspsp_key",
				"fieldtype": "Data",
				"label": "Enable Banking ASPSP Key",
				"description": "Stable provider key in COUNTRY::ASPSP format.",
				"insert_after": "swift_number",
				"no_copy": 1,
				"read_only": 1,
				"unique": 1,
			},
		],
		"Bank Account": [
			{
				"fieldname": "enable_banking_section",
				"fieldtype": "Section Break",
				"label": "Enable Banking",
				"insert_after": "integration_details_section",
				"collapsible": 1,
			},
			{
				"fieldname": "enable_banking_account",
				"fieldtype": "Link",
				"label": "Enable Banking Account",
				"options": "Enable Banking Account",
				"insert_after": "enable_banking_section",
				"no_copy": 1,
				"read_only": 1,
				"unique": 1,
			},
			{
				"fieldname": "enable_banking_booked_balance",
				"fieldtype": "Currency",
				"label": "Enable Banking Booked Balance",
				"options": "enable_banking_balance_currency",
				"insert_after": "enable_banking_account",
				"no_copy": 1,
				"read_only": 1,
			},
			{
				"fieldname": "enable_banking_available_balance",
				"fieldtype": "Currency",
				"label": "Enable Banking Available Balance",
				"options": "enable_banking_balance_currency",
				"insert_after": "enable_banking_booked_balance",
				"no_copy": 1,
				"read_only": 1,
			},
			{
				"fieldname": "enable_banking_balance_currency",
				"fieldtype": "Link",
				"label": "Enable Banking Balance Currency",
				"options": "Currency",
				"insert_after": "enable_banking_available_balance",
				"no_copy": 1,
				"read_only": 1,
			},
			{
				"fieldname": "enable_banking_balance_as_of",
				"fieldtype": "Datetime",
				"label": "Enable Banking Balance As Of",
				"insert_after": "enable_banking_balance_currency",
				"no_copy": 1,
				"read_only": 1,
			},
			{
				"fieldname": "enable_banking_last_sync_at",
				"fieldtype": "Datetime",
				"label": "Enable Banking Last Sync At",
				"insert_after": "enable_banking_balance_as_of",
				"no_copy": 1,
				"read_only": 1,
			},
		],
		"Bank Transaction": [
			{
				"fieldname": "enable_banking_section",
				"fieldtype": "Section Break",
				"label": "Enable Banking",
				"insert_after": "transaction_type",
				"collapsible": 1,
			},
			{
				"fieldname": "enable_banking_account",
				"fieldtype": "Link",
				"label": "Enable Banking Account",
				"options": "Enable Banking Account",
				"insert_after": "enable_banking_section",
				"allow_on_submit": 1,
				"in_standard_filter": 1,
				"no_copy": 1,
				"read_only": 1,
			},
			{
				"fieldname": "enable_banking_transaction_key",
				"fieldtype": "Data",
				"label": "Enable Banking Transaction Key",
				"description": "SHA-256 idempotency key generated by the integration.",
				"insert_after": "enable_banking_account",
				"allow_on_submit": 1,
				"hidden": 1,
				"length": 64,
				"no_copy": 1,
				"read_only": 1,
				"unique": 1,
			},
		],
	}
